version: "3.8"
services:
  angular-service:
    container_name: angular-container2
    build: ./
    volumes:
      - "./:/usr/src/app"
    ports:
      - "4200:90"
    command: >
      bash -c "npm start"
  #   container_name: docker-nginx
  #  build: ./
  # ports:
  #  - "90:90"
  #command: ["nginx", "-g", "daemon off;"]
  #links:
  # - angular-service

#  docker-nginx:
